### PR TITLE
FIx Ingots

### PR DESCRIPTION
**Pull request by Iclario**
Sorry for the late, could you, please, remake your pull request

### CODE REVIEW

**Comment by fewizz** [comment]
and what now?

**Comment by fewizz** [comment]
create new PR?

**Comment by Iclario** [comment]
Yep

**Comment by fewizz** [comment]
I doing something wrong? right?

**Comment by fewizz** [comment]
revert reverted "Nevermine", and merge fixed ingots

**Comment by Iclario** [comment]
The Pull request is not mergeable right now

**Pull request merged**
